### ISSUE TITLE
Please submit a new version to Packagist

### ISSUE THREAD

**Issue by martinhartmann** [paydirekt/paydirekt-php#8]
Please submit a new version to Packagist, with [paragonie/random_compat](https://github.com/paragonie/random_compat) version ^2.0.11 included which was merged in ec6e20bdaf8cba7e43420bee4845c2709b7a532b and is four months old.

I'm using [roave/security-advisories](https://packagist.org/packages/roave/security-advisories) in one of our packages and can't update, because [paragonie/random_compat](https://github.com/paragonie/random_compat) v1 has known vulnerabilities. I also don't want to use dev-master on your package.

**Comment by stombers-senacor** [comment]
Hi @martinhartmann,
thanks for your request. The required version v0.4.0 is now available at Packagist.
